language: node_js
os:
  - linux
  - osx
dist: xenial
node_js:
  - '12'

jobs:
  include:
    - stage: test
      script:
        - cd platforms/$TRAVIS_OS_NAME
        - npm install
        - npm run build
      deploy:
        provider: npm
        email: govyazin@mixbytes.io
        on:
          branch: master
        api_key:
          secure: $DEPLOY_KEY

    - stage: buildDeploy
      os:
        - linux
      script:
        - npm run build
      deploy:
        provider: npm
        email: govyazin@mixbytes.io
        on:
          branch: master
        api_key:
          secure: $DEPLOY_KEY

