language: node_js
node_js:
  - "12"

cache:
  directories:
    - ~/.cmake-js/boost/

os:
  - linux
  - osx

dist: xenial

before_install:
  - sudo apt-get install -y libxml3-dev

install:
  - npm install
  - npm run build

