stages:
  - install

jobs:
  include:
    - stage: build
      language: node_js
      node_js:
        - "12
      os:
        - linux
        - osx
        - windows
      install:
        - npm install
      script:
        - npm run build
        - ls /
        - ls
