dist: xenial
node_js:
  - '12'

os:
  - linux
  - osx

jobs:
  include:
    - stage: test
      os:
        - linux
        - osx
      script:
        - npm i
        - cd platforms/$TRAVIS_OS_NAME
        - npm i
        - npm run build
      deploy:
        provider: npm
        email: govyazin@mixbytes.io
        on:
          branch: master
        api_key:
          secure: $DEPLOY_KEY

    - stage: buildDeploy
      os:
        - linux
      script:
        - npm i
        - npm run build
      deploy:
        provider: npm
        email: govyazin@mixbytes.io
        on:
          branch: master
        api_key:
          secure: $DEPLOY_KEY

