language: node_js
node_js:
  - "12"

stages:
  - install
  - build
  - test

jobs:
  include:
    - stage: build
      os:
        - linux
        - osx
      script:
        - npm run build
        - ls /
